### ISSUE TITLE
TBC Classic Version

### ISSUE THREAD

**Issue by yt0k** [frozn/ScrollingCombatText#1]
This is a shot in the dark, but are you able to post a working version for WoW TBC Classic? Your 9.1 fix shows up in the classic addons panel, the in game menu works but that is all. Thanks for your help!

Eidt: All testing functions within the addon work, but when getting into combat with mobs or players, no events fire.

**Comment by frozn** [comment]
fixed with commit 8eb275abc3f4986e2829613f5027f9bfba661efb and release [v9.1_1](https://github.com/frozn/ScrollingCombatText/releases/tag/v9.1_1)
